### PR TITLE
Look for first input with autofocus attribute

### PR DESCRIPTION
**Pull request by trsteel88**
Updated the focus method so it looks for an input with autofocus attribute as priority.

At the moment I have a fancybox launching which has a form. However, there is a link that precedes that form. Currently fancybox is attempting to focus on the first link rather than the first input field.

Adding a <input name="username" autofocus="autofocus" /> anywhere to that form will prioritise it over links.

### CODE REVIEW

**Comment by trsteel88** [comment]
@fancyapps any chance we can get this merged in?

**Comment by fancyapps** [comment]
@trsteel88 Hi, This will be included in the next commit.

**Comment by trsteel88** [comment]
Thanks @fancyapps :)

**Comment by trsteel88** [comment]
@fancyapps I can see a release went out 2 days ago. However, this wasn't merged?

**Comment by fancyapps** [comment]
@trsteel88 Hi, Your suggestion is actually included in the latest code. I usually do not merge code to keep track of versioning and almost always I like to tweak the code to my liking. 

You are probably asking this, because autofocus does not seem to work, the reason is that now `autoFocus` default value is changed to `false`. While auto-focusing by default seems to be great idea, it turns out that in real-life usage, this brings more confusion than any benefit. The issue is that if inline content height is larger than viewport and it has some button, then it will be scrolled down, and that is not the desired result, there were even some bug reports about.

**Pull request closed without merging**
