### PR TITLE
added "unquote" wrapper function

### PR DESCRIPTION
**Pull request by light-flight**
#2153 Trying to solve this issue.
Added unquote wrappers.
Ran `gulp`

### CODE REVIEW

**Comment by fancyapps** [comment]
Hi,

Sorry, but this looks messy and I believe that you try to fix non-existing issue.

**Comment by brooksco** [comment]
Isn't this still an issue?

**Comment by fancyapps** [comment]
The only issue is that you do not want to separate .css files from .scss and therefore your .css files can not contain perfectly valid CSS code that would improve quality of your design (e.g., your design will never look good on iPhones with the notch).

**Comment by brooksco** [comment]
I get that this is valid css, but sometimes we don't have control over changing our build pipeline to accommodate what's an unfortunate and clearly shared issue. Our css files _are_ separated, but it is helpful to be able to include css back into scss for our Webpack builds, and this issue (while ultimately a problem with other libraries) is a blocker for that process.

It's also not helpful to assume that whatever anyone else is working on will "never look good" on notched devices—we have plenty of notch handling in our codebase that utilizes the unquote method. What this issue does mean is that we are stuck on the `3.5.2` version of Fancybox, and cannot upgrade until someone takes initiative and fixes this issue. It would be great for it to be Fancybox that does that, but ultimately we'll likely move off of it or continue to sit on an older version.

**Comment by fancyapps** [comment]
Sorry, but that is just ridiculous to ask to include an ugly hack for everyone (yes, it will be for every single person even if he does not want or need) just because someone is too lazy to change they (bad) workflow.

**Pull request closed without merging**
