### PR TITLE
Fix fractional image end dimensions after zooming in

### PR DESCRIPTION
**Pull request by shred**
When zooming into an image after clicking on its thumbnail, I noticed that the image in the browser didn't look as sharp as the original image. The reason is that in the surrounding "fancybox-image-wrap" div, the width and height CSS attributes contained a fractional number that made the image slightly bigger than its actual dimensions.

Example: Actual image size: 1280 x 720 px. div size containing the image: 1281.34 x 720.83 px (figures are from my memory and may not be accurate).

The browser had to upscale the image a very little bit, which resulted in loss of sharpness.

This patch removes that the scale factor is rounded by two decimal places, which turned out to be the culprit of the rounding errors. Also, the animation target size is always rounded so the browser does not need to scale images on a sub-pixel level.

### CODE REVIEW

**Comment by fancyapps** [comment]
Hi,

Thanks for your work! 

I have included your code into my development version, but I replaced `Math.round` with `Math.floor` to fix #1512 issue caused by rounding. This will be included in the next update (v3.2.0)

**Comment by shred** [comment]
I hope `Math.floor` is the right choice, as it might round 1279.99 to 1279 px instead of 1280 px, which would lead to one-pixel scaling again. But this is just gut feeling. If the result is allright, it's fine with me. :smile: Thank you!

**Comment by fancyapps** [comment]
Hi,

I believe this has been incorporated in the code some time ago, just forget to close this pull request.

**Comment by shred** [comment]
Yes... Incorporating the changes under your name, and then dropping my PR isn't very motivating, though.

**Comment by fancyapps** [comment]
Hmm, true. Sorry, I had not thought about it that way. Thanks for pointing out.

**Pull request closed without merging**
