### PR TITLE
Preload images from AJAX response body

### PR DESCRIPTION
**Pull request by Borzik**
This PR allows images included in AJAX response body to be preloaded using imagesLoaded library before content is actually displayed.
##### New option

There is a new setting, `preloadAjaxImages`, which is `false` by default (so it works are previously). 
##### New dependency

It introduces new dependency: imagesLoaded library (added to `/lib` folder). If the feature is not used, `imagesLoaded` may be omitted as it will be called only if there is an AJAX type of Fancybox and `preloadAjaxImages` is set to `true`.
##### Behavior update

When `preloadAjaxImages` is set to `true`, AJAX response body will be parsed as HTML with jQuery, then passed to imagesLoaded, and only then `_afterLoad` callback will be called.
When `imagesLoaded` is not available, it will send a warning to console but will still work as if `preloadAjaxImages` setting was `false`.

### CODE REVIEW

**Comment by Borzik** [comment]
It will fix #494 and #800 as well, because I had exactly the same issue: images were not showing on initial load at all, but on the second one – they appeared just fine.

**Comment by fancyapps** [comment]
Sorry, see #800

**Comment by Borzik** [comment]
It's not always possible to have width/height stored for each image. But it's up to you to decide whether to merge it or not.
For anyone looking for a fix of this issue (and those who find #800 and #494 ): you can use this PR as a reference of what should be updated to enable that functionality, it's only a few lines of code + ImagesLoaded library.

**Comment by fancyapps** [comment]
Yes, thank you for your work. 
I just wanted to remind that the best practice is to show content as fast as possible, use content templates, etc., because users really hate staring at loading icon.

**Pull request closed without merging**
