### PR TITLE
Correction on bower.json

### PR DESCRIPTION
**Pull request by didaxRedux**
"main" section must contain relative path to distribution folders.

### CODE REVIEW

**Comment by didaxRedux** [comment]
Please accept pull request to solve issue when installing library with bower-installer.

**Comment by fancyapps** [comment]
Are you sure that this is the correct syntax? I`m not experienced bower user, but I tested and it worked fine.
Also, even bower example contains simple links https://github.com/bower/spec/blob/master/json.md

```JS
  "main": [
    "js/motion.js",
    "sass/motion.scss"
  ]
```

**Comment by didaxRedux** [comment]
You are definitely right.
The strange thing is that using bower-installer comes out an error due 
to the lack of this fix.

But maybe you're right: use official syntax and do not take into account 
issues due to third-party packages.

Thank you very much for your attention.

Il 12/05/17 21:26, Jānis Skarnelis ha scritto:

**Comment by fancyapps** [comment]
Maybe this is dues to fact that https://bower.io/ has this strange message:

`..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects!` 

Looks like bower is down - https://bower.io/stats/

**Comment by didaxRedux** [comment]
I think you are right.

Il giorno 13 Mag 2017 08:25, alle ore 08:25, "Jānis Skarnelis" <notifications@github.com> ha scritto:

**Pull request closed without merging**
